#   Copyright (c) MURANGWA Pacifique. and affiliates.
#   This source code is licensed under the Apache License 2.0 found in the
#   LICENSE file in the root directory of this source tree.


num1 = 100;
num2 = 200;

product = num1 * num2;
difference = num2 - num1;
sum = num2 + num1;
quotient = num1 / num2;
reminder = num2 % num1;

tangaza_amakuru(` product: ${product}, difference: ${difference}, sum: ${sum}, quotient: ${quotient}, reminder: ${reminder}`);