#   Copyright (c) MURANGWA Pacifique. and affiliates.
#   This source code is licensed under the Apache License 2.0 found in the
#   LICENSE file in the root directory of this source tree.


# demonstrating unary operators

num1 = 10;
num2 = 2;
ukuri = nibyo;

post_increment = num1++;  # post increment
post_decrement = num2--;  # post decrement

pre_increment = ++num1; # pre decrement
pre_decrement = --num2; # pre increment
ikinyoma = !ukuri; # negation

