#   Copyright (c) MURANGWA Pacifique. and affiliates.
#   This source code is licensed under the Apache License 2.0 found in the
#   LICENSE file in the root directory of this source tree.


# getting user's input from keyboard

num1 = injiza_amakuru `Enter num1:`;
num2 = injiza_amakuru `Enter num2:`;
num3 = injiza_amakuru `Enter num3:`;

average = (num1 + num2 + num3) / 3;

tangaza_amakuru `average is: ${average}`;