#ifndef KIN_ERROR_CODES
#define KIN_ERROR_CODES

typedef enum {
    ERROR_UNEXPECTED_CHARACTER, ERROR_UNTERMINATED_STRING_LITERAL,
    ERROR_FILE_NOT_FOUND, ERROR_INSUFFICIENT_MEMORY,
    ERROR_FAILED_TO_READ_FILE, ERROR_INVALID_TERMINAL_ARGUMENTS
} ErrorCodes;

#endif