import Parser from './parser/parser';
import Lexer from './lexer/lexer';
import { Interpreter } from './runtime/interpreter';
import { createGlobalEnv } from './runtime/globals';
import Environment from './runtime/environment';
import {
  MK_NUMBER,
  MK_STRING,
  MK_NULL,
  MK_BOOL,
  MK_OBJECT,
  MK_ARRAY,
  MK_NATIVE_FN,
  RuntimeVal,
  StringVal,
  NumberVal,
  BooleanVal,
  ObjectVal,
  ArrayVal,
  FunctionValue,
  NullVal,
  ClassVal,
  InstanceVal,
  BoundMethodVal,
  TypeVal,
  typeOfValue,
  TYPE_NULL,
  TYPE_NUMBER,
  TYPE_BOOLEAN,
  TYPE_STRING,
  TYPE_OBJECT,
  TYPE_ARRAY,
  TYPE_FN,
  TYPE_CLASS,
  TYPE_TYPE,
} from './runtime/values';
import {
  KinError,
  KinSyntaxError,
  KinTypeError,
  KinReferenceError,
  KinRuntimeError,
  isKinError,
  isKinSyntaxError,
  isKinTypeError,
  isKinReferenceError,
  isKinRuntimeError,
  createKinError,
  kinError,
  formatKinError,
  categoryForCode,
  CODE_CATEGORY,
} from './lib/errors';
import { renderKinError, renderThrown } from './lib/render-error';

export {
  Parser,
  Lexer,
  Interpreter,
  createGlobalEnv,
  Environment,
  MK_NUMBER,
  MK_STRING,
  MK_NULL,
  MK_BOOL,
  MK_OBJECT,
  MK_ARRAY,
  MK_NATIVE_FN,
  typeOfValue,
  TYPE_NULL,
  TYPE_NUMBER,
  TYPE_BOOLEAN,
  TYPE_STRING,
  TYPE_OBJECT,
  TYPE_ARRAY,
  TYPE_FN,
  TYPE_CLASS,
  TYPE_TYPE,
  KinError,
  KinSyntaxError,
  KinTypeError,
  KinReferenceError,
  KinRuntimeError,
  isKinError,
  isKinSyntaxError,
  isKinTypeError,
  isKinReferenceError,
  isKinRuntimeError,
  createKinError,
  kinError,
  formatKinError,
  categoryForCode,
  CODE_CATEGORY,
  renderKinError,
  renderThrown,
};

export type {
  RuntimeVal,
  StringVal,
  NumberVal,
  BooleanVal,
  ObjectVal,
  ArrayVal,
  FunctionValue,
  NullVal,
  ClassVal,
  InstanceVal,
  BoundMethodVal,
  TypeVal,
};

export type {
  KinErrorName,
  KinErrorCategoryCode,
  KinErrorCode,
  KinErrorOptions,
} from './lib/errors';
