import Parser from './parser/parser';
import Lexer from './lexer/lexer';
import { Interpreter } from './runtime/interpreter';
import { createGlobalEnv } from './runtime/globals';
import Environment from './runtime/environment';
import {
  MK_NUMBER,
  MK_STRING,
  MK_NULL,
  MK_BOOL,
  MK_OBJECT,
  MK_ARRAY,
  MK_NATIVE_FN,
  RuntimeVal,
  StringVal,
  NumberVal,
  BooleanVal,
  ObjectVal,
  ArrayVal,
  FunctionValue,
  NullVal,
} from './runtime/values';
import {
  KinError,
  KinSyntaxError,
  KinTypeError,
  KinReferenceError,
  KinRuntimeError,
  isKinError,
  isKinSyntaxError,
  isKinTypeError,
  isKinReferenceError,
  isKinRuntimeError,
  createKinError,
  kinError,
  formatKinError,
  categoryForCode,
  CODE_CATEGORY,
} from './lib/errors';
import { renderKinError, renderThrown } from './lib/render-error';
import {
  MANIFEST_FILE,
  LOCKFILE_FILE,
  MODULES_DIR,
  findProjectRoot,
  resolveInstalledPackage,
  initProject,
  installAll,
  addDependency,
  removeDependency,
  listPackages,
  listPackagesNamed,
  readManifest,
  writeManifest,
  readLockfile,
  parseSource,
  ManifestError,
  InstallError,
  InitError,
  SourceError,
} from './pkg';

export {
  Parser,
  Lexer,
  Interpreter,
  createGlobalEnv,
  Environment,
  MK_NUMBER,
  MK_STRING,
  MK_NULL,
  MK_BOOL,
  MK_OBJECT,
  MK_ARRAY,
  MK_NATIVE_FN,
  KinError,
  KinSyntaxError,
  KinTypeError,
  KinReferenceError,
  KinRuntimeError,
  isKinError,
  isKinSyntaxError,
  isKinTypeError,
  isKinReferenceError,
  isKinRuntimeError,
  createKinError,
  kinError,
  formatKinError,
  categoryForCode,
  CODE_CATEGORY,
  renderKinError,
  renderThrown,
  // Package manager
  MANIFEST_FILE,
  LOCKFILE_FILE,
  MODULES_DIR,
  findProjectRoot,
  resolveInstalledPackage,
  initProject,
  installAll,
  addDependency,
  removeDependency,
  listPackages,
  listPackagesNamed,
  readManifest,
  writeManifest,
  readLockfile,
  parseSource,
  ManifestError,
  InstallError,
  InitError,
  SourceError,
};

export type {
  RuntimeVal,
  StringVal,
  NumberVal,
  BooleanVal,
  ObjectVal,
  ArrayVal,
  FunctionValue,
  NullVal,
};

export type {
  KinErrorName,
  KinErrorCategoryCode,
  KinErrorCode,
  KinErrorOptions,
} from './lib/errors';
