name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '24.x'
      - run: npm ci
      - run: npm run test
      - run: npm run build
      - name: Run examples with the built language implementation
        run: npm run test:examples:cli
